version: "3.3"
services:
  redis:
    hostname: redis
    image: redis
    ports:
      - 6379:9379
  order_tracker:
    build:
      context: ./
      dockerfile: ./orders/dockerfile
    container_name: order_tracker
    links:
      - redis
      - tmapi_proxy
    depends_on:
      - redis
      - tmapi_proxy
    hostname: orders
    command: >
      pipenv run python run_orders.py
  tmapi_proxy:
    build:
      context: ./
      dockerfile: ./tmapi/dockerfile
    container_name: tmapi_proxy
    links:
      - redis
    depends_on:
      - redis
    hostname: tmapi_proxy
    command: >
      pipenv run python run_tmapi.py
    ports:
      - 8080
  oktell_proxy:
    build:
      context: ./
      dockerfile: ./oktell/dockerfile
    container_name: oktell_proxy
    links:
      - redis
      - tmapi_proxy
    ports:
      - 24055:8080
    depends_on:
      - redis
      - tmapi_proxy
    hostname: oktell_proxy
    command: >
      pipenv run python run_oktell.py
  payments:
    build:
      context: ./
      dockerfile: ./payment/dockerfile
    container_name: payment
    links:
      - redis
      - tmapi_proxy
    depends_on:
      - redis
      - tmapi_proxy
    hostname: payment
    command: >
      pipenv run python run_payment.py

  sms:
    build:
      context: ./
      dockerfile: ./sms/dockerfile
    container_name: sms
    links:
      - redis
      - tmapi_proxy
    depends_on:
      - redis
      - tmapi_proxy
    hostname: sms
    comman: >
      pipenv run python run_sms.py
