version: "3.3"
services:
  # redis:
  #   hostname: redis
  #   image: redis

  #   ports:
  #     - 0.0.0.0:6379:9379
  #   sysctls:
  #     - net.core.somaxconn=4096
  # - vm.overcommit_memory=1

  order_tracker:
    build:
      context: ./
      dockerfile: ./orders/dockerfile
    volumes:
      - /var/log:/orders/orders/logs
    container_name: order_tracker
    links:
      # - redis
      - tmapi_proxy
    depends_on:
      # - redis
      - tmapi_proxy
    hostname: orders
    command: >
      pipenv run python run_orders.py

  tmapi_proxy:
    build:
      context: ./
      dockerfile: ./tmapi/dockerfile
    volumes:
      - /var/log:/tmapi/tmapi/logs
    container_name: tmapi_proxy
    # links:
    #   - redis
    # depends_on:
    #   - redis
    hostname: tmapi_proxy
    command: >
      pipenv run python run_tmapi.py
    ports:
      - 8080

  oktell_proxy:
    build:
      context: ./
      dockerfile: ./oktell/dockerfile
    volumes:
      - /var/log:/oktell/oktell/logs
    container_name: oktell_proxy
    links:
      # - redis
      - tmapi_proxy
    ports:
      - 24055:24055
    depends_on:
      # - redis
      - tmapi_proxy
    hostname: oktell_proxy
    command: >
      pipenv run python run_oktell.py

  payments:
    build:
      context: ./
      dockerfile: ./payment/dockerfile
    volumes:
      - /var/log:/payment/payment/logs
    container_name: payment
    links:
      # - redis
      - tmapi_proxy
    depends_on:
      # - redis
      - tmapi_proxy
    hostname: payment
    restart: on-failure
    command: >
      pipenv run python run_payment.py

  sms:
    build:
      context: ./
      dockerfile: ./sms/dockerfile
    volumes:
      - /var/log:/sms/sms/logs
    container_name: sms
    links:
      # - redis
      - tmapi_proxy
    depends_on:
      # - redis
      - tmapi_proxy
    hostname: sms
    command: >
      pipenv run python run_sms.py
