databases:
  tme_db:
    database: tme_db
    user: postgres
    password: postgres
    host: 192.168.222.179
    port: 5432
    minsize: 1
    maxsize: 10

redis:
  host: 192.168.222.21
  # host: redis

tmtapi:
  host: 192.168.222.211
  port: 8089
  solt: "1292"
